### PR TITLE
➕ Add default values to roles

### PR DESCRIPTION
**Pull request by bdsoha**
# Proposed Changes

- Add default values to roles to refrain from missing values in the `all.yml` file.
- Allow modular use of roles when consumed as a collection.
- Add metadata to all roles with documented arguments. 

## Checklist

- [ ] Tested locally
- [ ] Ran `site.yml` playbook
- [ ] Ran `reset.yml` playbook
- [ ] Did not add any unnecessary changes
- [ ] Ran pre-commit install at least once before committing
- [ ] 🚀

### CODE REVIEW

**Comment by bdsoha** [comment]
@timothystewart6 It would be great to receive your input on whether or not such a PR is in the roadmap for this project. 
If so, I will continue the work for all other roles.

**Comment by bdsoha** [comment]
@timothystewart6 Did you have a chance to look at this?

**Comment by timothystewart6** [comment]
> @timothystewart6 Did you have a chance to look at this?

Hi!  Yes, this sounds great as long as we don't break any how it currently works.  Unfortunately CI isn't working right now but I hope to have it working soon so that the tests will run!

Thanks!
Tim

**Comment by timothystewart6** [comment]
Just let me know when this is ready!

**Comment by bdsoha** [comment]
No problem, I will change the PR status from *draft* to *ready*.

**Comment by bdsoha** [comment]
@timothystewart6 Ready for review!

**Comment by timothystewart6** [comment]
@bdsoha  it seems this is failing CI

see logs: https://github.com/techno-tim/k3s-ansible/actions/runs/10134226628/job/28020331172

**Comment by bdsoha** [comment]
@timothystewart6 I didn't choose the variable names, just used the existing ones *(which might cause regression failures for users of the playbook)*.
Therefore, I added *ignore* statements to the relevant lines.

`pre-commit` is passing locally for me.

**Comment by timothystewart6** [comment]
We'll they were only in a template before now they are set as defaults and used elsewhere.

**Comment by bdsoha** [comment]
@timothystewart6 
You are referring to a CI run from a previous commit *(before I added the ignore statements)*.
There is no CI run for [the most recent commit](https://github.com/techno-tim/k3s-ansible/pull/509/commits/273fd2e42d6eb8c018ca34182e76bda927d32e1d) which resolves the issues.

The most recent commit is `"requires approval from a maintainer"`.

**Comment by bdsoha** [comment]
@timothystewart6 Done!

**Comment by timothystewart6** [comment]
Unfortunately it's not passing CI

**Pull request merged**
