### PR TITLE
Change to FQCN with ansible-lint fixer

### PR DESCRIPTION
**Pull request by rholmboe**
# Proposed Changes

Since ansible-base 2.10 (later ansible-core), FQCN is the new way to go.

Updated .ansible-lint with a production profile and removed fqcn in skip_list. Updated .yamllint with rules needed.

Ran ansible-lint --fix=all, then manually applied some minor changes.

## Checklist

- [X] Tested locally
- [X] Ran `site.yml` playbook
- [ ] Ran `reset.yml` playbook
- [X] Did not add any unnecessary changes
- [X] Ran pre-commit install at least once before committing
- [ ] 🚀

### CODE REVIEW

**Comment by berendt** [comment]
I think this only makes sense if a CI test is also added to ensure that automatic formatting is always applied in future. We do this with Black for Python, for example. A test runs in the CI that executes Black and if it makes changes, the test fails.

**Comment by rholmboe** [comment]
> I think this only makes sense if a CI test is also added to ensure that automatic formatting is always applied in future. We do this with Black for Python, for example. A test runs in the CI that executes Black and if it makes changes, the test fails.

According to already defined CI jobs, it will execute pre-commit run which includes ansible-lint test that will fail if something isn't according to configured standard. So already in place

**Comment by timothystewart6** [comment]
Hey, thank you!  Sounds good!  I want to get a few PRs merge in first, which might break your PR but you should be able to fix it easily with `ansible-lint --fix=all` rather than breaking all of the other current PRs.

**Comment by timothystewart6** [comment]
@rholmboe sorry about the wait but I wanted merge the other PRs before this since this PR has a lot of style changes.

**Comment by rholmboe** [comment]
> @rholmboe sorry about the wait but I wanted merge the other PRs before this since this PR has a lot of style changes.

No worries, let me know when I can resolve conflicts and upload a new patch.

**Comment by berendt** [comment]
> > @rholmboe sorry about the wait but I wanted merge the other PRs before this since this PR has a lot of style changes.
> 
> No worries, let me know when I can resolve conflicts and upload a new patch.

All pending PRs merged. I think you can do a rebase & resolve conflicts.

**Comment by rholmboe** [comment]
PR updated, ready for review

**Comment by timothystewart6** [comment]
@rholmboe   it seems like the build is failing.

**Comment by rholmboe** [comment]
> @rholmboe it seems like the build is failing.

Yup, applied fix. yamllint failed on octal, something ansible-lint have in ignore.

**Comment by timothystewart6** [comment]
Thank you!

**Comment by rholmboe** [comment]
@timothystewart6 no worries man, thank you for creating this and making life easier for the rest of us!

**Pull request merged**
