### PR TITLE
Use sample inventory for Vagrant

### PR DESCRIPTION
**Pull request by sleiner**
# Proposed Changes
- Previously, `Vagrantfile` redefined all group and host variables. So changes to `inventory/sample` were not tested in CI.
- This PR uses `inventory/sample` for Vagrant.

## Checklist

- [x] Tested locally
- [x] Ran `site.yml` playbook
- [ ] Ran `reset.yml` playbook
- [x] Did not add any unnecessary changes
- [x] 🚀

### CODE REVIEW

**Comment by twistedgrim** [comment]
Why not use Molecule? https://molecule.readthedocs.io/en/latest/

**Comment by timothystewart6** [comment]
side note, it seems the the CI tasks still fails often

**Comment by sleiner** [comment]
> side note, it seems the the CI tasks still fails often but I think this is another race condition and I will try to fix it

Nice, thank you! 😊 And now with #57 being merged into `master`, the cache should save the need of downloading boxes from HashiCorp - so no more `429`s (as long as we stick to the same image) 🙌

**Comment by sleiner** [comment]
Concerning molecule: I'm still experimenting with it. However, if it works, I will open a separate PR for it. The core part of this PR are the changes to the host vars, which will be needed to use the sample inventory in CI - regardless of whether we use molecule or Vagrant directly.

**Comment by sleiner** [comment]
closing this in favor of #67...

**Pull request closed without merging**
