### PR TITLE
added fix for metallb version upgrades

### PR DESCRIPTION
**Pull request by egandro**
# Proposed Changes
For whatever reason metallb keeps an empty replica set when upgrading to a new version. There are 0/0 replicas running. It just sticks there.

- this fix allowes metallb to be upgraded via the playbooks

## Checklist

- [x] Tested locally
- [x] Ran `site.yml` playbook
- [x] Ran `reset.yml` playbook
- [x] Did not add any unnecessary changes
- [x] Ran pre-commit install at least once before committing
- [x] 🚀

Tested with all variations from

```txt
metal_lb_speaker_tag_version: "v0.13.9"
metal_lb_controller_tag_version: "v0.13.9"

to

metal_lb_speaker_tag_version: "v0.13.12"
metal_lb_controller_tag_version: "v0.13.12"
```

Test Code

```bash
kubectl version -o json 2>/dev/null | jq -r '.serverVersion.gitVersion'

POD=$(kubectl -n metallb-system get pod -l "component=controller,app=metallb" -o jsonpath="{.items[0].metadata.name}")
kubectl --namespace metallb-system exec -it ${POD} -- /controller version | head -n 1 | jq -rM '.version'

POD=$(kubectl -n metallb-system get pod -l "component=speaker,app=metallb" -o jsonpath="{.items[0].metadata.name}")
kubectl --namespace metallb-system exec -it ${POD} -- /bin/sh -c '/speaker version || true' | head -n 1 | jq -rM '.version' || true

POD=$(kubectl -n kube-system get pod -l "name=kube-vip-ds" -o jsonpath="{.items[0].metadata.name}")
kubectl --namespace kube-system exec -it ${POD} -- /kube-vip version | grep Version | sed -e 's/^.*v//g'
```

### CODE REVIEW

**Comment by onedr0p** [comment]
What's the purpose of deleting previous replicasets? What problem are you trying to solve?

**Comment by egandro** [comment]
> What's the purpose of deleting previous replicasets? What problem are you trying to solve?

This problem: https://github.com/techno-tim/k3s-ansible/blob/e880f08d26989299cdd1b8a39f7e1f7c8a85f163/roles/k3s_server_post/tasks/metallb.yml#L53

As there is a 0/0 line in the replicasets - and a new 1/1 the quoted code doesn't work.

Also the 0/0 with the old image doesn't serve any purpose.

**Comment by egandro** [comment]
> This PR is failing tests. If you want this to be merged it will need to be fixed 😅. Thank you!

I think I fixed it. It was a missing

```bash
  args:
    executable: /bin/bash
```

**Comment by timothystewart6** [comment]
Thank you!

**Comment by egandro** [comment]
I don't understand the issue with that test failing. It reports some nginx not being there.

Can you please enlighten me? or much better - how do I run these tests on my own setup? I know that there is some (direct) github action (local) runner. Can you point me to some documentation please?

Thx.

**Comment by timothystewart6** [comment]
I am going to run the tests again, this might have been a side effect of switching to self hosted runners.  Stay tuned!

**Comment by timothystewart6** [comment]
Disregard, it was the runners!  Thank you for the PR!

**Pull request merged**
