### PR TITLE
Variable documentation

### LINKED ISSUE #560: Document Variables
We should document variables and how to use them. Something as simple as an MD table in `README.md` would be nice but am open to other ideas.

| Variable | Default | Required | Description |
|---|---|---|---|
| k3s_version | none | yes | The version of k3s to use |
| ansible_user | none | yes | The ansible user that will be used |

etc...

### PR DESCRIPTION
**Pull request by 4t1l4**
# Proposed Changes

- Add variable documentation. 

Closes #560 

## Checklist

- [ ] Tested locally
- [ ] Ran `site.yml` playbook
- [ ] Ran `reset.yml` playbook
- [x] Did not add any unnecessary changes
- [x] Ran pre-commit install at least once before committing
- [ ] 🚀

### CODE REVIEW

**Comment by 4t1l4** [comment]
Hi, this is still WIP, but I'd appreciate some early feedback.

The table in the main README is starting to get big, the horizontal scroll is not great. There are a few ways to go about this but I'm not sure which would be best so anything maintainers like is good to me.

I'm trying to keep the descriptions as they are in the `argument_specs` and only adding things where there's a `choices` argument or where there was no description, because I'm using `ansible-doc` to help me do this and it doesn't like it when an option or sub-option doesn't have one.

**Comment by timothystewart6** [comment]
@4t1l4 wow!  This looks great!  I am sure everyone will appreciate this contribution!

**Comment by 4t1l4** [comment]
OK, ready for review now. Happy to adapt anything to make things easier to read or better structured. I'm very glad there's no MD linting in the hooks because that table would need a lot of tinkering with to fit the usual standards (I'd just stick some HTML instead if I had to).

**Comment by 4t1l4** [comment]
On a side note: 

I noticed that some of the default values for 3rd party stuff (version tags) will get stale soon. I looked into those defaults in the roles and don't see any dependabot config there to manage it. I'm used to sticking custom regex with Renovate, but don't know if this is possible with dependabot. Happy to work on that on a separate PR so we get automated dep updates both in the code and the docs.

**Comment by timothystewart6** [comment]
@4t1l4   thank you!  That would be awesome if you could figure out the regex for the container tags that are specified in `k3s-ansible/inventory/sample/group_vars/all.yml`

**Comment by 4t1l4** [comment]
I created #608 for the dependency management stuff.

**Pull request merged**
