### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by sleiner**
# Proposed Changes
- **Update pre-commit actions**
  This was done by running `pre-commit autoupdate --freeze`.
- **Remove pre-commit only dependencies from requirements.in**
  Including them in the file would create the illusion that those were the versions actually used in CI, but they are not.
  The exact versions are determined by the pre-commit hooks which are pinned in `.pre-commit-config.yaml`.

## Checklist

- [x] Tested locally
- [x] Ran `site.yml` playbook
- [x] Ran `reset.yml` playbook
- [x] Did not add any unnecessary changes
- [x] Ran pre-commit install at least once before committing
- [x] 🚀

### CODE REVIEW

**Comment by timothystewart6** [comment]
Thank you @sleiner   super close, just looks like a few lint rules!

**Comment by sleiner** [comment]
Yup - there are quite a few new ones now 😅 I'll fix these.

**Comment by timothystewart6** [comment]
Thank you!  I think we'll want to  update our github actions to also use python 3.11 instead of 3.10, right?

https://github.com/techno-tim/k3s-ansible/blob/master/.github/workflows/test.yml
https://github.com/techno-tim/k3s-ansible/blob/master/.github/workflows/lint.yml

**Comment by timothystewart6** [comment]
@sleiner   what do you think?

**Comment by timothystewart6** [comment]
I'll follow up to this in a PR

**Comment by timothystewart6** [comment]
Thank you @sleiner !!

**Pull request merged**
