### PR TITLE
Replace hardcoded 'master' group name with 'group_name_master' variable

### PR DESCRIPTION
**Pull request by berendt**
# Proposed Changes

For improved flexibility and maintainability.

* Update tasks in node role to use 'group_name_master' variable instead of hardcoded 'master' group name
* Update tasks in master role to use 'group_name_master' variable instead of hardcoded 'master' group name
* Update tasks in post role to use 'group_name_master' variable instead of hardcoded 'master' group name

## Checklist

- [x] Tested locally
- [x] Ran `site.yml` playbook
- [x] Ran `reset.yml` playbook
- [x] Did not add any unnecessary changes
- [x] Ran pre-commit install at least once before committing
- [x] 🚀

### CODE REVIEW

**Comment by timothystewart6** [comment]
Thank you!  While I do like this idea, I feel like this should be backwards compatible.  Any way to make this default to `master` if this variable is not provided?

**Comment by timothystewart6** [comment]
@berendt  looks like yaml lint

**Comment by berendt** [comment]
Looks like pre-commit uses a different yamllint configuration then ``.yamllint``? The line-length should be a warning only.

```
---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
```

**Comment by timothystewart6** [comment]
Good call, I will look into it.  Might need to load the config...

**Comment by timothystewart6** [comment]
Thank you!

**Pull request merged**
