### PR TITLE
feat(k3s): Updated to v1.25

### PR DESCRIPTION
**Pull request by timothystewart6**
# Proposed Changes

- updated `k3s` to the `1.25` release branch
- `v1.25.x`
-  update `kube-vip` to `0.5.12`

## Checklist

- [x] Tested locally
- [x] Ran `site.yml` playbook
- [x] Ran `reset.yml` playbook
- [x] Did not add any unnecessary changes
- [x] Ran pre-commit install at least once before committing
- [x] 🚀

### CODE REVIEW

**Comment by timothystewart6** [comment]
I am holding off on this a little bit because kubernetes 1.25 has a lot of breaking changes and although nothing with this bootstrapper will break, services people try to install later may not work.  I would rather not take on that kind of support right now, nor tell everyone to use the 1.24 version.  Keeping this open for now.

**Comment by J-eremy** [comment]
At this point rancher isn't even compatible yet for 1.25. So good call.

**Comment by timothystewart6** [comment]
Although I don't want to couple the two too tightly, that is definitely one of the hold outs!  Anyone is free to bump the version themselves too :)

**Comment by timothystewart6** [comment]
It seems like most things are compatible with 1.25 now.  Will consider merging after the next k3s release.

**Comment by timothystewart6** [comment]
As soon as the build passes I will release it

**Pull request merged**
