### PR TITLE
Documented k3s_single_node variable in group_vars/all.yaml

### PR DESCRIPTION
**Pull request by jurlwin**
# Proposed Changes

I documented the k3s_single_node variable in all.yaml.  Comments only...
-
-
-

## Checklist

- [ x] Tested locally
- [ x] Ran `site.yml` playbook
- [ x] Ran `reset.yml` playbook
- [ x] Did not add any unnecessary changes
- [ x] 🚀

### CODE REVIEW

**Comment by sleiner** [comment]
@jurlwin FYI: #95 proposes to replace that variable altogether

**Comment by jurlwin** [comment]
> @jurlwin FYI: #95 proposes to replace that variable altogether

personally -- this change makes things more complicated for me -- not that i'm not about to propose another change that may not be good for others, but this #95  change hits me right now - negatively.

I have 4 nodes, 3 are masters to test/validate HA and 1 is a worker bee.  I'm waiting for a few more RPI CM4s to become available so that I do have/end up with multiple notes.  I plan on installing longhorn to test storage, etc., so for me, this "automagic" tainting will be more of a headache.  I *think* i get why, but...maybe we should have a bit more control over it than based upon counts of items, etc...

**Comment by sleiner** [comment]
> maybe we should have a bit more control over it than based upon counts of items, etc...

I agree 👍🏻 #95 moves the taint to the group vars file, so you do get control over it, at least as far as I see. Or are you wishing for something else? In any case, if you have questions or concerns regarding #95, let's discuss them there 😊

**Comment by timothystewart6** [comment]
I think this was superseded by https://github.com/techno-tim/k3s-ansible/pull/95

**Pull request closed without merging**
