### PR TITLE
Override less Ansible settings

### PR DESCRIPTION
**Pull request by sleiner**
# Proposed Changes

- Do not perform privilege escalation by default (for examples of problems caused by this, see #223)
- Do not disable host key checking by default (that is unsafe)
- Do not mute deprecation warnings by default

## Checklist

- [x] Tested locally
- [x] Ran `site.yml` playbook
- [x] Ran `reset.yml` playbook
- [x] Did not add any unnecessary changes
- [x] Ran pre-commit install at least once before committing
- [x] 🚀

### CODE REVIEW

**Review by sleiner — COMMENTED** [review]
General question: Should we have an `ansible.cfg` file in this repo at all? As far as I see, none of those settings are relevant to this specific playbook - so IMO, all of those should be configured at the user rather than the playbook level. @timothystewart6, what do you think?

**Comment by timothystewart6** [comment]
@sleiner Good question.  I feel like we should probably delete this, commit the delete, add it to `.gitignore`.  This should be up to each developer to configure and should not be tracked for changes.

We could also create a `ansible.cfg.example` that has these values that does get committed with a note somewhere in the `README.md` that instructs them to rename it to `ansible.cfg` and modify to their liking.  The second part is up to you, but I do like to give examples of configs with sensible defaults.

**Comment by timothystewart6** [comment]
Thank you! Note to myself that I will have to update https://github.com/techno-tim/techno-tim.github.io/blob/master/_posts/2022-03-26-k3s-etcd-ansible.md to include creating / renaming this file so that the video / docs match what's here

**Comment by timothystewart6** [comment]
Thank you!

**Comment by timothystewart6** [comment]
docs updated https://github.com/techno-tim/techno-tim.github.io/commit/d0912e8e45e2e8cac9b580a19c1f0029bb1e0191

**Pull request merged**
