### PR TITLE
Removing accidental tear-down step that is clearly a typo

### PR DESCRIPTION
**Pull request by inadarei**
# Proposed Changes
Found a suspicious task in setup/Ubuntu that removes `linux-modules-extra-raspi` immediately after adding it. Feels like a typo that accidentally copied what should be in teardown, into setup. 

However, the consequences of  this are severe, since Ubuntu k3s setup without linux-modules-extra-raspi is extremely unstable and thus the rest of the setup is compromised. 

Indeed, when I run site.yml on RPIs with Ubuntu, the setup doesn't complete successfully. It eventually hangs. Which is what sent me on the quest to debug it, and I think this typo may be at least one of the culprits. 

## Checklist

- [x] Tested locally
- [x] Ran `site.yml` playbook
- [x] Ran `reset.yml` playbook
- [x] Did not add any unnecessary changes
- [x] 🚀

### CODE REVIEW

**Comment by sleiner** [comment]
Thanks! That is indeed a typo.

> the consequences of this are severe

As far as I see, this should not have any consequences, since the step is only executed if `state == "absent"`, but the whole file is only used if `state == "present"`. Still, this is obviously wrong and confusing and should be removed :-)

> when I run site.yml on RPIs with Ubuntu, the setup doesn't complete successfully. It eventually hangs.

At what step does it hang?

**Comment by timothystewart6** [comment]
Looks like there's a lint issue, otherwise GTG.  Thank you!

**Comment by timothystewart6** [comment]
@inadarei just waiting on the lint fix, then GTG!

**Comment by timothystewart6** [comment]
Ignore the lint fixes, this was caused by pip requirements not being frozen.  I fixed this in #119  and will merge it in after it merges

**Comment by timothystewart6** [comment]
Thank you!

**Pull request merged**
