### PR TITLE
CI: Fix linting job for ansible-lint 6.6.0

### PR DESCRIPTION
**Pull request by sleiner**
# Proposed Changes

- Fix linting job

## Checklist

- [ ] Tested locally
- [ ] Ran `site.yml` playbook
- [ ] Ran `reset.yml` playbook
- [x] Did not add any unnecessary changes
- [x] 🚀

### CODE REVIEW

**Comment by ioagel** [comment]
fix the linting action and then use my pull request (without the change I did in the linting action). I fix all the linting problems that make the job fail.

**Comment by sleiner** [comment]
@ioagel first of all: sorry for that! The explanation is quite simple: I did not see your PR in time, I have just looked at it a few minutes ago 😬
Still, I think there is value to fixing the linter job without requiring the more sophisticated changes from #95 first.

But if you want to, I will gladly resolve the conflicts in your PR for you 😊

**Comment by sleiner** [comment]
Seems there is a new flakiness in town :/
If this happens again, we might have to add a retry mechanism here...
 https://github.com/techno-tim/k3s-ansible/actions/runs/3092105672/jobs/5004611238#step:7:367

**Comment by ioagel** [comment]
> @ioagel first of all: sorry for that! The explanation is quite simple: I did not see your PR in time, I have just looked at it a few minutes ago 😬 Still, I think there is value to fixing the linter job without requiring the more sophisticated changes from #95 first.
> 
> But if you want to, I will gladly resolve the conflicts in your PR for you 😊

you are right… about the linter… I hacked my way to fixing stuff!

**Comment by timothystewart6** [comment]
Thank you!

**Pull request merged**
