### PR TITLE
Option to disable strict host key check

### PR DESCRIPTION
**Pull request by maxcerny**
# Proposed Changes

- Add a variable to disable host key checking

## Checklist

- [x] Tested locally
- [x] Ran `site.yml` playbook
- [x] Ran `reset.yml` playbook
- [x] Did not add any unnecessary changes
- [ ] Ran pre-commit install at least once before committing
- [ ] 🚀

### CODE REVIEW

**Comment by maxcerny** [comment]
Makes it easier to deploy on infrastructure deployed by Terraform.

That might be a good expansion to this. I have a terraform config for deploying the VMs inside proxmox, and creating a new VLAN in MikroTik.

**Comment by timothystewart6** [comment]
I think this can be handled in your `ansible.cfg`?

```
[defaults]
host_key_checking = False
```

**Comment by maxcerny** [comment]
> I think this can be handled in your `ansible.cfg`?
> 
> ```
> [defaults]
> host_key_checking = False
> ```

it should, but last time i tried i didn't have much success with that setting going through for some reason...

**Comment by timothystewart6** [comment]
Thank you for this.  I do think I am going to close the PR however since [this](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#host-key-checking) should be solved in your [ansible config](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#the-configuration-file).  I appreciate you taking the time to open a PR!

**Pull request closed without merging**
