### PR TITLE
feat(k3s): Updated to v1.27

### PR DESCRIPTION
**Pull request by timothystewart6**
# Proposed Changes

- Updated k3s to the 1.27 release
- v1.27.9
- Updated Debian testing image to 12

## Checklist

- [x] Tested locally
- [x] Ran `site.yml` playbook
- [x] Ran `reset.yml` playbook
- [x] Did not add any unnecessary changes
- [x] Ran pre-commit install at least once before committing
- [x] 🚀

### CODE REVIEW

**Comment by 3deep5me** [comment]
Could we merge this?

**Comment by timothystewart6** [comment]
Hey, sorry this is only being kept open for testing new versions against CI.

**Comment by djonko** [comment]
Hi, has anyone tried this.. The 1.27? Could I have any feedback please?

**Comment by timothystewart6** [comment]
CI has tested it, you can check the actions above.  Otherwise not sure about real world

**Comment by djonko** [comment]
thanks !!! I am going to try  it today on my proxmox Vms kubernetes

**Comment by 3deep5me** [comment]
site.yaml seems to work:
image

**Comment by timothystewart6** [comment]
Nice!

**Comment by djonko** [comment]
image

- ks3: v1.27.3+k3s1
- kube_vip_tag_version: "v0.6.0"
- metal_lb_frr_tag_version: "v8.5.2"
- metal_lb_speaker_tag_version: "v0.13.10"
- metal_lb_controller_tag_version: "v0.13.10"

**Comment by alexolivier** [comment]
Would be keen for this to be merged if possible

**Comment by timothystewart6** [comment]
> Would be keen for this to be merged if possible

See the comment in the first post

**Comment by pbolduc** [comment]
1.27.4 works fine on a 5 node raspberry pi cluster,

image

**Pull request merged**
